import type { Metadata } from "next"
import CactuBlinkingLines from "@fet/dynamicBackgrounds/CactuBlinkingLines"
import "./reset.css"
import "./globals.css"
import classes from "./layout.module.css"
import { cactuFont, geistMonoFont, geistSansFont } from "@fet/theme/fonts"

export const metadata: Metadata = {
  title: `Create Next App`,
  description: `Generated by create next app`,
}

export type RootLayoutProps = Readonly<{
  children: React.ReactNode
}>

export default function RootLayout({ children }:RootLayoutProps) {
  return (
    <html lang="pl">
      <body className={`${geistSansFont.variable} ${geistMonoFont.variable} ${cactuFont.variable}`}>
        <CactuBlinkingLines className={classes.background} />
        {children}
      </body>
    </html>
  )
}
